######################################################################
# Automatically generated by qmake (2.01a) ?? ???? 2 17:51:41 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
#CONFIG += debug

# Input
HEADERS += galaxians.h
SOURCES += galaxians.cpp main.cpp
